on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - "staging"
          - "prod"
      run_ui_test:
        description: 'Run UI testing'
        required: true
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.set_status.outputs.status }}
    steps:
      - name: Checkosut Source Code
        uses: actions/checkout@v7.0.0
        with:
          repository: ${{github.repository}}
          ref: ${{github.ref_name}}
      - name: list files in workspaces
        run: ls ${{github.workspace}}
      - name: Set an output status
        id: set_status
        run: echo "status=success" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run UI tests
        if: ${{ inputs.run_ui_test }}
        run: echo "Running UI testing tools"