Name: My Workflow

On:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run it manually

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
       - name: Run a one-line script
         run: echo Hello, world!